"""
This type stub file was generated by pyright.
"""

class Barometer:
    '''Barometer facade.

    Barometer sensor is used to measure the ambient air pressure in hPa.

    With method `enable` you can turn on pressure sensor and 'disable'
    method stops the sensor.

    Use property `pressure` to get current air pressure in hPa.

    .. versionadded:: 1.2.5

    Supported Platforms:: Android, iOS
    '''
    @property
    def pressure(self):
        '''Current air pressure in hPa.'''
        ...
    
    def enable(self): # -> None:
        '''Enable barometer sensor.'''
        ...
    
    def disable(self): # -> None:
        '''Disable barometer sensor.'''
        ...
    


