"""
This type stub file was generated by pyright.
"""

'''
Flash
=====

The :class:`Flash` provides access to public methods to use flash of your
device.

.. note::
    In android you need CAMERA, FLASHLIGHT permissions
    to access flash.

.. versionadded:: 1.2.5

This can be used to activate the flash of your camera on
Android and iOS.

Simple Examples
---------------

To turn on flash::

    >>> from plyer import flash
    >>> flash.on()

To turn off flash::

    >>> flash.off()

To release flash::

    >>> flash.release()

Supported Platforms
-------------------
Android, iOS

'''
class Flash:
    """
    Flash facade.
    """
    def on(self): # -> None:
        """
        Activate the flash
        """
        ...
    
    def off(self): # -> None:
        """
        Deactiavte the flash
        """
        ...
    
    def release(self): # -> None:
        """
        Release any access to the Flash / Camera.
        Call this when you're done using the Flash.
        This will release the Camera, and stop any process.

        Next call to `_on` will reactivate it.
        """
        ...
    


