"""
This type stub file was generated by pyright.
"""

class Gravity:
    '''Gravity facade.

    .. versionadded:: 1.2.5

    Supported Platforms:: Android

    '''
    @property
    def gravity(self):
        '''Property that returns values of the current gravity force
        as a (x, y, z) tuple. Returns (None, None, None)
        if no data is currently available.
        '''
        ...
    
    def enable(self): # -> None:
        '''Activate the gravity sensor. Throws an error if the
        hardware is not available or not implemented on.
        '''
        ...
    
    def disable(self): # -> None:
        '''Disable the gravity sensor.
        '''
        ...
    


