"""
This type stub file was generated by pyright.
"""

class Humidity:
    '''Humidity facade.
       Humidity sensor returns value of humidity.
       With method `enable` you can turn on Humidity sensor and
       'disable' method stops the sensor.
       Use property `tell` to get humidity value.

       Supported Platforms
       -------------------
       Android
    '''
    @property
    def tell(self):
        '''Current humidity'''
        ...
    
    def enable(self): # -> None:
        '''Enable Humidity sensor.'''
        ...
    
    def disable(self): # -> None:
        '''Disable Humidity sensor.'''
        ...
    


