"""
This type stub file was generated by pyright.
"""

'''
IrBlaster
============

The :class:`IrBlaster` provides access to public methods by which your device
can act as a remote and could be used to control your TV, AC, Music Player,
Projectors, Set top box or anything that can be controlled by a remote.

.. note::
    - On Android your app needs the TRANSMIT_IR permission which allows an
    application to use the device's IR transmitter, If available.

Simple Examples
---------------

To get transmit an IR sequence::

    >>> from plyer import irblaster
    >>> irblaster.transmit(frequency, pattern, mode)

To get frequencies::

    >>> irblaster.frequencies

To check if IrBlaster exists::

    >>> irblaster.exists()
    True/False

Supported Platforms
-------------------
Android

'''
class IrBlaster:
    '''
    Infrared blaster facade.
    '''
    @staticmethod
    def periods_to_microseconds(frequency, pattern): # -> list[Unknown]:
        '''
        Convert a pattern from period counts to microseconds.
        '''
        ...
    
    @staticmethod
    def microseconds_to_periods(frequency, pattern): # -> list[Unknown]:
        '''
        Convert a pattern from microseconds to period counts.
        '''
        ...
    
    @property
    def frequencies(self):
        '''
        Property which contains a list of frequency ranges
           supported by the device in the form:

           [(from1, to1),
            (from2, to2),
            ...
            (fromN, toN)]
        '''
        ...
    
    def get_frequencies(self):
        ...
    
    def transmit(self, frequency, pattern, mode=...):
        '''
        Transmit an IR sequence.

        :parameters:
            `frequency`: int
                Carrier frequency for the IR transmission.
            `pattern`: list[int]
                Burst pair pattern to transmit.
            `mode`: str, defaults to 'period'
                Specifies the format of the pattern values.
                Can be 'period' or 'microseconds'.
        '''
        ...
    
    def exists(self):
        '''
        Check if the device has an infrared emitter.
        '''
        ...
    


