"""
This type stub file was generated by pyright.
"""

class Light:
    '''Light facade.

    Light sensor measures the ambient light level(illumination) in lx.
    Common uses include controlling screen brightness.

    With method `enable` you can turn on the sensor and
    `disable` method stops the sensor.

    Use property `illumination` to get current illumination in lx.

    .. versionadded:: 1.2.5

    Supported Platforms:: Android
    '''
    @property
    def illumination(self):
        '''Current illumination in lx.'''
        ...
    
    def enable(self): # -> None:
        '''Enable light sensor.'''
        ...
    
    def disable(self): # -> None:
        '''Disable light sensor.'''
        ...
    


