"""
This type stub file was generated by pyright.
"""

class SpatialOrientation:
    '''Spatial Orientation facade.

    Computes the device's orientation based on the rotation matrix.

    .. versionadded:: 1.3.1
    '''
    @property
    def orientation(self): # -> tuple[None, None, None]:
        '''Property that returns values of the current device orientation
        as a (azimuth, pitch, roll) tuple.

        Azimuth, angle of rotation about the -z axis. This value represents the
        angle between the device's y axis and the magnetic north pole.
        The range of values is -π to π.

        Pitch, angle of rotation about the x axis. This value represents the
        angle between a plane parallel to the device's screen and a plane
        parallel to the ground.
        The range of values is -π to π.

        Roll, angle of rotation about the y axis. This value represents the
        angle between a plane perpendicular to the device's screen and a plane
        perpendicular to the ground.
        The range of values is -π/2 to π/2.

        Returns (None, None, None) if no data is currently available.

        Supported Platforms:: Android
        '''
        ...
    
    def enable_listener(self): # -> None:
        '''Enable the orientation sensor.
        '''
        ...
    
    def disable_listener(self): # -> None:
        '''Disable the orientation sensor.
        '''
        ...
    


