"""
This type stub file was generated by pyright.
"""

class Temperature:
    '''Temperature facade.

    Temperature sensor is used to measure the ambient room temperature in
    degrees Celsius (°C)
    With method `enable` you can turn on temperature sensor and 'disable'
    method stops the sensor.
    Use property `temperature` to get ambient air temperature in degree C.

    .. versionadded:: 1.2.5

    Supported Platforms:: Android

    '''
    @property
    def temperature(self):
        '''Current air temperature in degree C.'''
        ...
    
    def enable(self): # -> None:
        '''Enable temperature sensor.'''
        ...
    
    def disable(self): # -> None:
        '''Disable temperature sensor.'''
        ...
    


