"""
This type stub file was generated by pyright.
"""

'''
Wifi Facade.
=============

The :class:`Wifi` is to provide access to the wifi of your mobile/ desktop
devices.

It currently supports `connecting`, `disconnecting`, `scanning`, `getting
available wifi network list` and `getting network information`.

Simple examples
---------------

To enable/ turn on wifi scanning::

    >>> from plyer import wifi
    >>> wifi.start_scanning()

Once the wifi is enabled/ turned on, then this command starts to scan
all the nearby available wifi networks.

To get network info::

    >>> from plyer import wifi
    >>> wifi.start_scanning()
    >>> return wifi.get_network_info(name)

Returns network details of the network who's name/ssid is provided in the
`name` parameter.

To connect to a network::

    >>> from plyer import wifi
    >>> wifi.start_scanning()
    >>> wifi.connect(network, parameters)

This connects to the network who's name/ssid is provided under `network`
parameter and along with other necessary methods for connection
which depends upon platform to platform.

please visit following files for more details about requirements of
`paramaters` argument in `connect` method:

    plyer/platforms/win/wifi.py
    plyer/platforms/macosx/wifi.py
    plyer/platforms/win/wifi.py

To disconnect from wifi::

    >>> from plyer import wifi
    >>> wifi.disconnect()

This disconnects your device from any wifi network.

To get available wifi networks::

    >>> from plyer import wifi
    >>> wifi.start_scanning()
    >>> return wifi.get_available_wifi()

This returns all the available wifi networks near the device.

Supported Platforms
-------------------
Windows, OS X, Linux

Ex: 6
----------

from plyer import wifi
wifi.enable()

This enables wifi device.

Ex: 7
----------

from plyer import wifi
wifi.disable()

This disable wifi device
'''
class Wifi:
    '''
    Wifi Facade.
    '''
    def is_enabled(self):
        '''
        Return enabled status of WiFi hardware.
        '''
        ...
    
    def is_connected(self, interface=...):
        '''
        Return connection state of WiFi interface.

        .. versionadded:: 1.4.0
        '''
        ...
    
    @property
    def interfaces(self):
        '''
        List all available WiFi interfaces.

        .. versionadded:: 1.4.0
        '''
        ...
    
    def start_scanning(self, interface=...):
        '''
        Turn on scanning.
        '''
        ...
    
    def get_network_info(self, name):
        '''
        Return a dictionary of specified network.
        '''
        ...
    
    def get_available_wifi(self):
        '''
        Returns a list of all the available wifi.
        '''
        ...
    
    def connect(self, network, parameters, interface=...): # -> None:
        '''
        Method to connect to some network.
        '''
        ...
    
    def disconnect(self, interface=...): # -> None:
        '''
        To disconnect from some network.
        '''
        ...
    
    def enable(self): # -> None:
        '''
        Wifi interface power state is set to "ON".
        '''
        ...
    
    def disable(self): # -> None:
        '''
        Wifi interface power state is set to "OFF".
        '''
        ...
    


